# Generated by Django 4.0.5 on 2022-06-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_shedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='email',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='from_time',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='to_time',
            field=models.CharField(default='', max_length=20),
        ),
    ]
