# Generated by Django 4.0.5 on 2022-06-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_shedule', '0003_schedule_created_at_schedule_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='user_type',
            field=models.CharField(default='', max_length=30),
        ),
    ]
